rss_groups:
  Tech: &tech
    9to5 : https://9to5linux.com/category/news/feed
    Tech : https://www.404media.co/rss
    Android Authority : https://www.androidauthority.com/feed
    Artificial Intelligence (AI) : https://www.reddit.com/r/artificial/.rss
    BBC tech : https://feeds.bbci.co.uk/news/technology/rss.xml
    CNN Tech : http://rss.cnn.com/rss/edition_technology.rss
    Engadget: https://www.engadget.com/rss.xml
    freeCodeCamp.org: https://www.youtube.com/feeds/videos.xml?channel_id=UC8butISFwT-Wl7EV0hUK0BQ
    Gadgets 360: https://feeds.feedburner.com/gadgets360-latest
    FOSS News: https://news.itsfoss.com/rss
    NY times technology : https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
    
chat_ids:
  8028896761:
    <<: *tech
