rss_groups:
  group_1: &Ri
    rss_1: https://www.reddit.com/r/broslikeus.rss
    rss_2: https://www.reddit.com/r/BigAndMuscular.rss
  
    rss_3: https://www.reddit.com/r/VlinesAbsAndDick.rss
chat_ids: 
8028896761:
    <<: *Ri
