rss_groups:
  技术: &tech
    美团技术团队: https://www.repeatsoftware.com/help/RSSFeedList.htm
  博客: &blog
    月光博客:
      url: http://feeds.bbci.co.uk/news/world/rss.xml
      fold: true
    阮一峰的网络日志: http://feeds.bbci.co.uk/news/technology/rss.xml
  新闻: &new
    FT中文网: http://www.ftchinese.com/rss/news
  综合: &other
    少数派: https://sspai.com/feed

chat_ids:
  8028896761:
    <<: *tech
    <<: *blog
    <<: *new
    <<: *other
