rss_groups:
  group_1: R1
    rss_1: https://www.reddit.com/r/ladybonersgw.rss
    rss_2: https://www.reddit.com/r/BigAndMuscular.rss
  group_2: R2
    rss_3: https://www.reddit.com/r/BigAndMuscular.rss

chat_ids:
  8028896761:
    <<: *R1
    <<: *R2
    
